/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectjava;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class dataDiri extends javax.swing.JFrame {

    /**
     * Creates new form dataDiri
     */
    public dataDiri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoKambing = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        boxNama = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        boxEmail = new javax.swing.JTextField();
        noHp = new javax.swing.JLabel();
        boxNoHp = new javax.swing.JTextField();
        alamat = new javax.swing.JLabel();
        boxAlamat = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        boxPassword = new javax.swing.JTextField();
        selesai = new javax.swing.JButton();
        backround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoKambing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectjava/logokecil.png"))); // NOI18N
        jPanel1.add(logoKambing, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 180, -1));

        nama.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        nama.setText("Nama Lengkap");
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, -1));

        boxNama.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        boxNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNamaActionPerformed(evt);
            }
        });
        jPanel1.add(boxNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 420, 30));

        email.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        email.setText("Email");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        boxEmail.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        boxEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxEmailActionPerformed(evt);
            }
        });
        jPanel1.add(boxEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 310, 420, 30));

        noHp.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        noHp.setText("Handphone");
        jPanel1.add(noHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        boxNoHp.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(boxNoHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 420, 30));

        alamat.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        alamat.setText("Alamat Rumah");
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        boxAlamat.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(boxAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 420, 70));

        password.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        password.setText("Password Akun Anda");
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        boxPassword.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        boxPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(boxPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 420, 30));

        selesai.setBackground(new java.awt.Color(255, 255, 255));
        selesai.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        selesai.setText("SELESAI");
        selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiActionPerformed(evt);
            }
        });
        jPanel1.add(selesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 580, 90, 30));

        backround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectjava/a.jpg"))); // NOI18N
        jPanel1.add(backround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 630));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxNamaActionPerformed

    private void boxPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxPasswordActionPerformed

    public static String name;
    public static String pass;
    public static String emailData;
    public static String hp;
    public static String alamatData;
    
    private void selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiActionPerformed
        // TODO add your handling code here:
        name = boxNama.getText ();
        pass = boxPassword.getText();
        emailData = boxEmail.getText();
        hp = boxNoHp.getText();
        alamatData = boxAlamat.getText();
        
        if(name.length() == 0){
            JOptionPane.showMessageDialog(null, "Maaf mohon isi datanya semua :)");
        }else if(pass.length() == 0){
            JOptionPane.showMessageDialog(null, "Maaf mohon isi datanya semua :)");
        }else if(emailData.length() == 0){
            JOptionPane.showMessageDialog(null, "Maaf mohon isi datanya semua :)");
        }else if(hp.length() == 0){
            JOptionPane.showMessageDialog(null, "Maaf mohon isi datanya semua :)");
        }else if(alamatData.length() == 0){
            JOptionPane.showMessageDialog(null, "Maaf mohon isi datanya semua :)");
        }else{
            login sudah = new login(name, pass);
            
            sudah.setVisible (true);
            this.setVisible(false);
        }
        
        
    }//GEN-LAST:event_selesaiActionPerformed

    private void boxEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataDiri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataDiri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataDiri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataDiri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataDiri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat;
    private javax.swing.JLabel backround;
    private javax.swing.JTextField boxAlamat;
    private javax.swing.JTextField boxEmail;
    private javax.swing.JTextField boxNama;
    private javax.swing.JTextField boxNoHp;
    private javax.swing.JTextField boxPassword;
    private javax.swing.JLabel email;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoKambing;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel noHp;
    private javax.swing.JLabel password;
    private javax.swing.JButton selesai;
    // End of variables declaration//GEN-END:variables
}
