/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectjava;

import java.util.ArrayList;
import java.util.Iterator;
import javafx.collections.ObservableList;
import javax.swing.JOptionPane;
import static projectjava.dataDiri.name;

/**
 *
 * @author Muchsin
 */
public class kambing extends javax.swing.JFrame {

    /**
     * Creates new form kambing
     */
    public kambing() {
        initComponents();
    }
    
    public kambing(String name) {
        initComponents();
        nameLabel.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Pilih = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        bobot = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        Cek = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectjava/logoasli.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel3.setText("Jenis jenis Kambing Qurban");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setText("Jenis kambing");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        Pilih.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        Pilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Kambing Etawa", "Kambing Kacang", " ", " " }));
        Pilih.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                PilihItemStateChanged(evt);
            }
        });
        Pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihActionPerformed(evt);
            }
        });
        getContentPane().add(Pilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 170, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setText("Bobot");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        bobot.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bobotItemStateChanged(evt);
            }
        });
        bobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bobotActionPerformed(evt);
            }
        });
        getContentPane().add(bobot, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 210, 40));

        Cek.setText("Cek Harga");
        Cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CekActionPerformed(evt);
            }
        });
        getContentPane().add(Cek, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton1.setText("SETUJU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 100, -1));

        jButton2.setText("<< Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 110, -1));

        nameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectjava/a.jpg"))); // NOI18N
        getContentPane().add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void PilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_PilihActionPerformed

    private void bobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bobotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bobotActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nama = nameLabel.getText();
        String dataKambing = Pilih.getSelectedItem().toString();
        String beratKambing = bobot.getSelectedItem().toString();
        String hargaKambing = jTextField1.getText();
        
        kartuFinish kartu = new kartuFinish(nama,  dataKambing, beratKambing, hargaKambing);
        
        kartu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jenisQurban kembali2 = new jenisQurban ();
        kembali2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bobotItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bobotItemStateChanged
        
    }//GEN-LAST:event_bobotItemStateChanged

    private void PilihItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_PilihItemStateChanged
        ArrayList<String> array = new ArrayList<>();
        Iterator<String> iter;
        
        if(Pilih.getSelectedItem().equals("Kambing Etawa")){
            bobot.removeAllItems();
            array.add("80-85 Kg");
            array.add("85-90 Kg");
            iter = array.iterator();
            while(iter.hasNext()){
                bobot.addItem(iter.next());
            }
        }
        
        if(Pilih.getSelectedItem().equals("Kambing Kacang")){
            bobot.removeAllItems();
            array.add("35-40 Kg");
            array.add("40-50 Kg");
            iter = array.iterator();
            while(iter.hasNext()){
                bobot.addItem(iter.next());
            }
        }
        
        
    }//GEN-LAST:event_PilihItemStateChanged

    private void CekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CekActionPerformed
        if(Pilih.getSelectedItem().equals("Kambing Etawa")){
            if(bobot.getSelectedItem().equals("80-85 Kg")){
                jTextField1.setText("Rp. 2.500.000");
            }else if(bobot.getSelectedItem().equals("85-90 Kg")){
                jTextField1.setText("Rp. 2.750.000");
            }
        }
        else if(Pilih.getSelectedItem().equals("Kambing Kacang")){
            if(bobot.getSelectedItem().equals("35-40 Kg")){
                jTextField1.setText("Rp. 1.300.000");
            }else if(bobot.getSelectedItem().equals("40-50 Kg")){
                jTextField1.setText("Rp. 1.600.000");
            }
        }
    }//GEN-LAST:event_CekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kambing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kambing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kambing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kambing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kambing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cek;
    private javax.swing.JComboBox<String> Pilih;
    private javax.swing.JComboBox<String> bobot;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
