/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectjava;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class kartuFinish extends javax.swing.JFrame {

    /**
     * Creates new form kartuFinish
     */
    public kartuFinish() {
        initComponents();
    }
    
    public kartuFinish(String nama, String jenis, String berat, String harga){
        initComponents();
        String dataNama = "";
        String dataJenis = "";
        String dataBerat = "";
        String dataHarga = "";
        
        dataNama += nama;
        dataJenis += jenis;
        dataBerat += berat;
        dataHarga += harga;
        
        jTextField2.setText(dataNama);
        jTextField3.setText(dataJenis);
        jTextField4.setText(dataBerat);
        jTextField1.setText(dataHarga);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        logoDiri = new javax.swing.JLabel();
        selesai = new javax.swing.JButton();
        nama = new javax.swing.JLabel();
        nama1 = new javax.swing.JLabel();
        nama2 = new javax.swing.JLabel();
        nama3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        backround = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoDiri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectjava/diri.png"))); // NOI18N
        logoDiri.setText("jLabel1");
        jPanel1.add(logoDiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 158, 160));

        selesai.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        selesai.setText("SELESAI");
        selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiActionPerformed(evt);
            }
        });
        jPanel1.add(selesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 90, 30));

        nama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nama.setText("HARGA");
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 90, 10));

        nama1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nama1.setText("NAMA");
        jPanel1.add(nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 50, 10));

        nama2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nama2.setText("JENIS HEWAN");
        jPanel1.add(nama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 90, 10));

        nama3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nama3.setText("BERAT HEWAN");
        jPanel1.add(nama3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 90, 10));

        jTextField1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 170, -1));

        jTextField2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 170, -1));

        jTextField3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 170, -1));

        jTextField4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 170, -1));

        backround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectjava/farm.jpg"))); // NOI18N
        jPanel1.add(backround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog (null, "Data-Data Anda Berhasil Disimpan");
    }//GEN-LAST:event_selesaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kartuFinish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kartuFinish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kartuFinish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kartuFinish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kartuFinish().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backround;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel logoDiri;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nama1;
    private javax.swing.JLabel nama2;
    private javax.swing.JLabel nama3;
    private javax.swing.JButton selesai;
    // End of variables declaration//GEN-END:variables
}
