/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectjava;

import java.util.ArrayList;
import java.util.Iterator;

/**
 *
 * @author Muchsin
 */
public class sapi extends javax.swing.JFrame {

    /**
     * Creates new form sapi
     */
    public sapi() {
        initComponents();
    }
    
    public sapi(String nama) {
        initComponents();
        nameLabel.setText(nama);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Pilih = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        cek = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectjava/logo sapi - Copy.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel3.setText("Jenis jenis Sapi Qurban");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 220, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setText("Jenis Sapi");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        Pilih.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        Pilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Sapi Limousin", "Sapi Ongole", " ", " " }));
        Pilih.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                PilihItemStateChanged(evt);
            }
        });
        Pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihActionPerformed(evt);
            }
        });
        getContentPane().add(Pilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 170, 20));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setText("Bobot");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 210, 40));

        cek.setText("cek harga");
        cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekActionPerformed(evt);
            }
        });
        getContentPane().add(cek, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        jButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton1.setText("SETUJU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 100, -1));

        jButton2.setText("<< Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 110, -1));

        nameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectjava/a.jpg"))); // NOI18N
        getContentPane().add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PilihActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nama = nameLabel.getText();
        String dataSapi = Pilih.getSelectedItem().toString();
        String beratSapi = jComboBox1.getSelectedItem().toString();
        String hargaSapi = jTextField1.getText();
        
        kartuFinish kartu = new kartuFinish(nama,  dataSapi, beratSapi, hargaSapi);
        
        
        kartu.setVisible (true);
        this.setVisible (false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jenisQurban kembali1 = new jenisQurban ();
        kembali1.setVisible (true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PilihItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_PilihItemStateChanged
        ArrayList<String> array = new ArrayList<>();
        Iterator<String> iter;
        
        if(Pilih.getSelectedItem().equals("Sapi Limousin")){
            jComboBox1.removeAllItems();
            array.add("1,3 - 1,4 Ton");
            array.add("1,5 – 1,6 Ton");
            iter = array.iterator();
            while(iter.hasNext()){
                jComboBox1.addItem(iter.next());
            }
        }
        
        if(Pilih.getSelectedItem().equals("Sapi Ongole")){
            jComboBox1.removeAllItems();
            array.add("500 - 700 Kg");
            array.add("700 - 850 Kg");
            iter = array.iterator();
            while(iter.hasNext()){
                jComboBox1.addItem(iter.next());
            }
        }
    }//GEN-LAST:event_PilihItemStateChanged

    private void cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekActionPerformed
        if(Pilih.getSelectedItem().equals("Sapi Limousin")){
            if(jComboBox1.getSelectedItem().equals("1,3 - 1,4 Ton")){
                jTextField1.setText("Rp. 85.000.000");
            }else if(jComboBox1.getSelectedItem().equals("1,5 – 1,6 Ton")){
                jTextField1.setText("Rp. 92.000.000");
            }
        }
        else if(Pilih.getSelectedItem().equals("Sapi Ongole")){
            if(jComboBox1.getSelectedItem().equals("500 - 700 Kg")){
                jTextField1.setText("Rp. 17.000.000");
            }else if(jComboBox1.getSelectedItem().equals("700 - 850 Kg")){
                jTextField1.setText("Rp. 21.000.000");
            }
        }
    }//GEN-LAST:event_cekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sapi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sapi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sapi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sapi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sapi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Pilih;
    private javax.swing.JButton cek;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
